import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";
import "bootstrap/dist/css/bootstrap.min.css";
import Providers from "./providers";
import ClientShell from "./clientshell";



const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const jwt = (await cookies()).get("jwt")?.value ?? null; // string | null

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Providers>
          <ClientShell authToken={!!jwt}>
            {children}
          </ClientShell>
        </Providers>
      </body>
    </html>
  );
}