import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";
import "bootstrap/dist/css/bootstrap.min.css";
import Providers from "./providers";
import ClientShell from "./clientshell";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Ariflex",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const jwt = (await cookies()).get("jwt")?.value ?? null; // string | null

  return (
    <html lang="en" className={inter.className}>
      <body className={`${inter.className}`}>
        <Providers>
          <ClientShell authToken={!!jwt}>{children}</ClientShell>
        </Providers>
      </body>
    </html>
  );
}
